# project.toml
[general]
domain_threshold = 0.6
repositories_folder = "code_repositories"
HF_DATASETS_CACHE="/data/rech/ouedraoi"

[models]
embedder = "mixedbread-ai/mxbai-embed-large-v1"
llm = "huggingface"
model = "meta-llama/Meta-Llama-3-8B-Instruct"

[prompts]
suggestion = "prompts/suggestion.json"
entrypoint = "prompts/entrypoint.json"
justification = "prompts/justification.json"
