@startuml
class CurrentTransaction {
  id
  date
  description
  type
  status
  amount
  availableBalance
  currentAccount
  getId()()
  setId(Long)()
  getDate()()
  setDate(Date)()
  getDescription()()
  setDescription(String)()
  getType()()
  setType(String)()
  getStatus()()
  setStatus(String)()
  getAmount()()
  setAmount(double)()
  getAvailableBalance()()
  setAvailableBalance(BigDecimal)()
  getCurrentAccount()()
  setCurrentAccount(CurrentAccount)()
}
class CurrentAccount {
  id
  accountNumber
  accountBalance
  currentTransactionList
  getId()()
  setId(Long)()
  getAccountNumber()()
  setAccountNumber(int)()
  getAccountBalance()()
  setAccountBalance(BigDecimal)()
  getCurrentTransactionList()()
  setCurrentTransactionList(List)()
}
class SavingsAccount {
  id
  accountNumber
  accountBalance
  savingsTransactionList
  getId()()
  setId(Long)()
  getAccountNumber()()
  setAccountNumber(int)()
  getAccountBalance()()
  setAccountBalance(BigDecimal)()
  getSavingsTransactionList()()
  setSavingsTransactionList(List)()
}
class AccountController {
  userService
  accountService
  transactionService
  currentAccount(Model, Principal)()
  savingsAccount(Model, Principal)()
  deposit(Model)()
  depositPOST(String, String, Principal)()
  withdraw(Model)()
  withdrawPOST(String, String, Principal)()
}
@enduml
